version: '3'
services:
  slack-gpt-bot-sample:
    restart: always
    build: .
    container_name: 'slack-gpt-bot-sample'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    ports:
      - "3000:3000"
    command: flask run --host 0.0.0.0 --port 3000
    environment:
      - FLASK_APP=opt/web/app.py
